In [1]:
import numpy as np

In [24]:
with open("example5.txt", "r") as readfile:
    a = readfile.read()
    lines = a.split("\n")

In [3]:
def start_position(lines):
    #It checks where is the start position and returns its coordinates

    for idx, line in enumerate(lines):
        for idy, character in enumerate(line):
            if (character == 'S'):
                return (idx,idy)

In [4]:
def first_iteration(idx,idy):
    #It checks in clockwise direction starting from the north what is the next step in the path, and returns its coordinates
    #north
    if (lines[idx-1][idy] == '|'):
        return (idx-1, idy, "S")
   #north east
    elif (lines[idx-1][idy] == 'F'):
        return (idx-1, idy+1, "S")
    #east
    elif (lines[idx][idy+1] == '-'):
        return (idx, idy+1, "W")
    elif (lines[idx][idy+1] == '7'):
        return (idx+1, idy+1, 'N')
    #south east
    elif (lines[idx+1][idy+1] == 'L'):
        return (idx+1, idy+1, "W")
    #south
    elif (lines[idx+1][idy] == '|'):
        return (idx+1, idy, "N")
    #south west
    elif (lines[idx+1][idy-1] == 'J'):
        return (idx+1, idy-1, "N")
    #west
    elif (lines[idx][idy-1] == '-'):
        return (idx, idy-1, "E")
    #northwest
    elif (lines[idx-1][idy-1] == 'L'):
        return (idx-1, idy-1, "E")

In [5]:
def next_iterations(idx,idy,origen):
    #It computes the next coordinates of the path
    if (lines[idx][idy] == "|"):
        if (origen == "S"):
            return (idx-1, idy, "S")
        elif (origen == "N"):
            return (idx+1, idy, "N")
    elif (lines[idx][idy] == "-"):
        if (origen == "E"):
            return (idx,idy-1, "E")
        elif (origen == "W"):
            return (idx, idy+1, "W")
    elif (lines[idx][idy] == "L"):
        if (origen == "E"):
            return (idx-1, idy, "S")
        elif (origen == "N"):
            return (idx, idy+1, "W")
    elif (lines[idx][idy] == "J"):
        if (origen == "N"):
            return (idx, idy-1, "E")
        elif (origen == "W"):
            return (idx-1, idy, "S")
    elif (lines[idx][idy] == "7"):
        if (origen == "S"):
            return (idx, idy-1, "E")
        elif (origen == "W"):
            return (idx+1, idy, "N")
    elif (lines[idx][idy] == "F"):
        if (origen == "S"):
            return (idx, idy+1, "W")
        elif (origen == "E"):
            return (idx+1, idy, "N")
    elif (lines[idx][idy] == "S"):
        return "end"

In [6]:
def trail_func(lines):
    #It computes the path to be followed
    trail = []
    start = start_position(lines)
    trail.append(start)
    step = first_iteration(start[0], start[1])
    trail.append(step[0:2])

    while (step != "end"):
        step = next_iterations(step[0], step[1], step[2])
        if isinstance(step[0], int):
            trail.append(step[0:2])
    
    return trail
    

In [7]:
def zero_matrix(size_x, size_y):
    #It creates an empty matrix
    zero = np.zeros((size_x, size_y), dtype=int)
    return zero

In [25]:
zero = zero_matrix(len(lines), len(lines[0]))
left = zero_matrix(len(lines), len(lines[0]))
right = zero_matrix(len(lines), len(lines[0]))

for coord_x, coord_y in trail_func(lines):
    zero[coord_x][coord_y] = 1

In [26]:
n = 0

for ix, row in enumerate(zero):
    for iy, value in enumerate(row):
        if (value == 0) and (sum(zero[ix][(iy+1):])%2 != 0):
            left[ix][iy] = 2

In [27]:
zero

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0]])

In [28]:
left

array([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
n = 0

for ix, row in enumerate(zero):
    for iy, value in enumerate(reversed(row)):
        if (value == 0) and (sum(zero[ix][(iy+1):])%2 != 0):
            right[ix][iy] = 2

In [30]:
right = np.flip(right, axis=1)
right

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2]])

In [31]:
overlap = left + right

In [32]:
overlap

array([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2],
       [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2],
       [0, 2, 0, 2, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2],
       [2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2]])

In [33]:
n = 0

for row in overlap:
    for value in row:
        if value == 4:
            n = n + 1

In [34]:
n

2